version: '3.8'
services:
  app:
    image: tdc-api
    container_name: tdc-api-app
    build: 
      args:
        - PHP_VERSION=${PHP_VERSION}
        - OS_VERSION=${OS_VERSION}
      context: ./
      dockerfile: ./docker/prod/Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - local-network
  nginx: 
    image: nginx:${NGINX_VERSION}-alpine
    container_name: tdc-api-nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/prod/nginx:/etc/nginx/conf.d
    networks:
      - local-network
    ports:
      - 8000:8000
networks:
  local-network:
    driver: bridge